# Base configuration
exclude: [".rvmrc", ".rbenv-version", "README.md", "changelog.md"]
markdown: kramdown
highlighter: rouge
permalink: pretty


collections:
  pages:
    output: true
    permalink: /:path/

 Title: ğŸ’»âœ’ï¸ğŸ“„ğŸŒŸ
name: Kobby Nii Armah Aryeetey

# Author/Organization info to be displayed in the templates
author: Kobby Nii Armah Aryeetey
  name: Hohoe Municipal Information Technology Technician
  url: http://hhma.gov.gh

# When using this template with a project (repository) page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
baseurl: '/guides-template'

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/image.png
logoalt: Nii Armah 

- Navigation: CV, Portfolio, Tableau, About/Contact, Research
# List links that should appear in the site sidebar here
navigation:
- text: Introduction
  internal: true
  url: ./
- text: Add a new page
  internal: true
  url: add-a-new-page
- text: Configure the Guide
  internal: true
  url: configure-the-guide
- text: GitHub Setup
  internal: true
  url: github
- text: Create a Glossary
  glossary: true
- text: Edit this Repo
  internal: false
  url: https://github.com/iamthatnikah

# Repo list
# List repos that you would like to appear on the homepage here
repos:
- name: guides-template
  description:
  url: https://github.com/iamthatnikah

google_analytics_ua:

# Style Variables
brand_color: "#DA253B"
